// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaH7FTa2Py2CK3aV_yqJKX0LF8M9_q5JQ',
    appId: '1:483746948230:web:779baf6e0312e9c2e01d07',
    messagingSenderId: '483746948230',
    projectId: 'custom-erp-pos',
    authDomain: 'custom-erp-pos.firebaseapp.com',
    storageBucket: 'custom-erp-pos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcheVFgd9amG0eVyxSXaNlmlpgxEuswK4',
    appId: '1:483746948230:android:405fee62f8b0558fe01d07',
    messagingSenderId: '483746948230',
    projectId: 'custom-erp-pos',
    storageBucket: 'custom-erp-pos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtakYR6gvzOOb5Paj4mslq8zxX16hEn_0',
    appId: '1:483746948230:ios:7cbda9faf92bb664e01d07',
    messagingSenderId: '483746948230',
    projectId: 'custom-erp-pos',
    storageBucket: 'custom-erp-pos.firebasestorage.app',
    iosBundleId: 'com.example.customErp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtakYR6gvzOOb5Paj4mslq8zxX16hEn_0',
    appId: '1:483746948230:ios:7cbda9faf92bb664e01d07',
    messagingSenderId: '483746948230',
    projectId: 'custom-erp-pos',
    storageBucket: 'custom-erp-pos.firebasestorage.app',
    iosBundleId: 'com.example.customErp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaH7FTa2Py2CK3aV_yqJKX0LF8M9_q5JQ',
    appId: '1:483746948230:web:e4f770c68cb97851e01d07',
    messagingSenderId: '483746948230',
    projectId: 'custom-erp-pos',
    authDomain: 'custom-erp-pos.firebaseapp.com',
    storageBucket: 'custom-erp-pos.firebasestorage.app',
  );
}
